/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#e5bfa2",
        "secondary-container": "#c0f13e",
        "surface-container": "#e5eeff",
        "on-secondary-fixed": "#151f00",
        "surface-dark": "#0A1628",
        "secondary-fixed": "#c3f341",
        "surface-container-low": "#eff4ff",
        "primary-container": "#101c2e",
        "error-container": "#ffdad6",
        "surface-container-high": "#dce9ff",
        "tertiary": "#000000",
        "on-secondary-fixed-variant": "#3a4d00",
        "on-primary-container": "#79849b",
        "outline": "#75777d",
        "on-background": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#a8d620",
        "accent-lime": "#C4F542",
        "text-muted": "#64748B",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "tertiary-fixed": "#ffdcc2",
        "background-main": "#FFFFFF",
        "surface-bright": "#f8f9ff",
        "on-tertiary-container": "#9e7d64",
        "error": "#ba1a1a",
        "outline-variant": "#c5c6cd",
        "surface-tint": "#535f74",
        "inverse-primary": "#bbc7df",
        "on-surface-variant": "#45474c",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d7e3fc",
        "on-tertiary-fixed-variant": "#5c412b",
        "on-primary": "#ffffff",
        "inverse-surface": "#213145",
        "primary": "#000000",
        "primary-fixed-dim": "#bbc7df",
        "warning-amber": "#F59E0B",
        "on-primary-fixed": "#101c2e",
        "background": "#f8f9ff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3c475b",
        "on-tertiary-fixed": "#2b1705",
        "tertiary-container": "#2b1705",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "secondary": "#4e6700",
        "on-secondary-container": "#516b00",
        "success-green": "#10B981"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "container-max": "1280px",
        "unit": "8px",
        "margin-desktop": "40px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-xl": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
